name: prune_llm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=2.16=mkl
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2023.11.17=hbcca054_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cudatoolkit=11.3.1=hb98b00a_12
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.0=py39h3d6467e_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - glib=2.69.1=he621ea3_2
  - gmp=6.3.0=h59595ed_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.17.2=pyh41d4057_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py39hf3d152e_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.8.0=16_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.8.0=16_mkl
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=h21135ba_2
  - libpq=12.15=hdbd6064_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.46.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.8.0=py39h06a4308_0
  - matplotlib-base=3.8.0=py39h1128e8f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2020.2=256
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.22.4=py39hc58783e_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.1.4=hd590300_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py39ha612740_0
  - pip=23.3=py39h06a4308_0
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - prompt_toolkit=3.0.41=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - pyzmq=25.1.1=py39h8c080ef_2
  - qt-main=5.15.2=h327a75a_7
  - readline=8.2=h5eee18b_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py39h06a4308_0
  - torchaudio=0.10.1=py39_cu113
  - torchvision=0.11.2=py39_cu113
  - tornado=6.3.3=py39h5eee18b_0
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - argparse==1.4.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - beautifulsoup4==4.12.3
      - botorch==0.9.5
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - cryptography==42.0.1
      - data==0.4
      - dataproperty==1.0.1
      - datasets==2.15.0
      - dill==0.3.7
      - distro==1.8.0
      - einops==0.7.0
      - fastapi==0.104.1
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - funcsigs==1.0.2
      - future==0.18.3
      - gdown==5.0.0
      - gdrive==0.1.5
      - google-api-core==2.15.0
      - google-api-python-client==2.43.0
      - google-auth==2.27.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==0.5.3
      - googleapis-common-protos==1.62.0
      - gpytorch==1.11
      - h11==0.14.0
      - httpcore==1.0.2
      - httplib2==0.22.0
      - httptools==0.6.1
      - httpx==0.25.1
      - huggingface-hub==0.19.4
      - idna==3.4
      - jaxtyping==0.2.25
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonlines==4.0.0
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - kaleido==0.2.1
      - latex==0.7.0
      - linear-operator==0.5.1
      - lm-eval==0.3.0
      - markupsafe==2.1.3
      - mbstrdecoder==1.1.3
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multipledispatch==1.0.0
      - multiprocess==0.70.15
      - nbformat==5.9.2
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numexpr==2.8.7
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai==1.3.4
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.1.3
      - pathvalidate==3.2.0
      - peft==0.6.2
      - plotly==5.18.0
      - portalocker==2.8.2
      - protobuf==4.25.1
      - psutil==5.9.6
      - pyaml==23.12.0
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pycountry==22.3.5
      - pycparser==2.21
      - pydantic==1.10.13
      - pydantic-core==2.14.3
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pysocks==1.7.1
      - pytablewriter==1.2.0
      - python-dotenv==1.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - ray==2.8.0
      - referencing==0.31.0
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rouge-score==0.1.2
      - rpds-py==0.13.1
      - rsa==4.9
      - sacrebleu==1.5.0
      - safetensors==0.4.0
      - scienceplots==2.1.1
      - scikit-learn==1.3.2
      - scikit-optimize==0.9.0
      - scipy==1.11.4
      - seaborn==0.13.0
      - secretstorage==3.3.3
      - sentencepiece==0.1.99
      - setuptools==59.6.0
      - shutilwhich==1.1.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlitedict==2.1.0
      - starlette==0.27.0
      - sympy==1.12
      - tabledata==1.3.3
      - tcolorpy==0.1.4
      - tempdir==0.7.1
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tokenizers==0.15.0
      - torch==2.1.0
      - tqdm==4.66.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.35.2
      - triton==2.1.0
      - typeguard==2.13.3
      - typepy==1.3.2
      - tzdata==2023.3
      - uritemplate==4.1.1
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - versioneer==0.29
      - vllm==0.2.2
      - watchfiles==0.21.0
      - websockets==12.0
      - wheel==0.37.1
      - xformers==0.0.22.post7
      - xxhash==3.4.1
      - yarl==1.9.3
      - zstandard==0.22.0
prefix: /data/your_name/miniconda3/envs/prune_llm
